<?php

/**
 * Implements hook_init().
 */
function abtesting_init() {
  /*We'll be using jQuery.cookie provide by Drupal in core.
  This allow us creating, reading and deleting cookies.
  This library is not loaded unless specifically loaded.*/
  drupal_get_library('system', 'jquery.cookie');
  $path = drupal_get_path('module', 'abtesting');
  drupal_add_js($path . '/abtesting/abtesting.js');

  // Set here variables that need to be passed to javascript
  // A random number 1-10, users < 6, group-a, users >= 6, group-b
  // @todo -- move it to javascript
  $random = mt_rand(0, 10);

  if ($random < 6) {
    // User belong to group A
    $user_group = 'a';
  } else {
    $user_group = 'b';
  }

  $settings = array(
    'basePath' => $base_path;
    'userGroup' => $user_group;
  );
  drupal_add_js(array('abtesting' => $settings), 'settings');
}
